// <auto-generated />
namespace LibraryDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditAutorEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditAutorEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281426305_EditAutorEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
